version: '3'
services:
  app:
    build: .
    depends_on:
      - db

  db:
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_ROOT_HOST: "%"
    ports:
      - "33060:3306"
    volumes:
      - ./db/test_db:/docker-entrypoint-initdb.d