version: '3'
services:
  # db is in db folder
  db:
    build: db/.
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "33060:3306"

  # Application Dockerfile is in same folder which is .
  app:
    build: .
    depends_on:
      - db
    links:
      - db